# coding: utf-8

"""
    Perific API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Item(BaseModel):
    """
    Item
    """ # noqa: E501
    item_id: Optional[StrictInt] = Field(default=None, alias="ItemId")
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    system_name: Optional[StrictStr] = Field(default=None, alias="SystemName")
    item_category: Optional[StrictStr] = Field(default=None, alias="ItemCategory")
    item_type: Optional[StrictStr] = Field(default=None, alias="ItemType")
    item_sub_type: Optional[StrictStr] = Field(default=None, alias="ItemSubType")
    mac_address: Optional[StrictStr] = Field(default=None, alias="MacAddress")
    time_zone: Optional[StrictStr] = Field(default=None, alias="TimeZone")
    firmware: Optional[StrictStr] = None
    hardware: Optional[StrictStr] = None
    creation_time: Optional[StrictStr] = Field(default=None, alias="CreationTime")
    __properties: ClassVar[List[str]] = ["ItemId", "Name", "SystemName", "ItemCategory", "ItemType", "ItemSubType", "MacAddress", "TimeZone", "firmware", "hardware", "CreationTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ItemId": obj.get("ItemId"),
            "Name": obj.get("Name"),
            "SystemName": obj.get("SystemName"),
            "ItemCategory": obj.get("ItemCategory"),
            "ItemType": obj.get("ItemType"),
            "ItemSubType": obj.get("ItemSubType"),
            "MacAddress": obj.get("MacAddress"),
            "TimeZone": obj.get("TimeZone"),
            "firmware": obj.get("firmware"),
            "hardware": obj.get("hardware"),
            "CreationTime": obj.get("CreationTime")
        })
        return _obj


