# coding: utf-8

"""
    Perific API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from .latest_packets import LatestPackets
from typing import Optional, Set
from typing_extensions import Self

class LatestItemPackets(BaseModel):
    """
    LatestItemPackets
    """ # noqa: E501
    item_id: Optional[StrictInt] = Field(default=None, alias="ItemId")
    latest_packets: Optional[Dict[str, LatestPackets]] = Field(default=None, alias="LatestPackets")
    __properties: ClassVar[List[str]] = ["ItemId", "LatestPackets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LatestItemPackets from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in latest_packets (dict)
        _field_dict = {}
        if self.latest_packets:
            for _key_latest_packets in self.latest_packets:
                if self.latest_packets[_key_latest_packets]:
                    _field_dict[_key_latest_packets] = self.latest_packets[_key_latest_packets].to_dict()
            _dict['LatestPackets'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LatestItemPackets from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ItemId": obj.get("ItemId"),
            "LatestPackets": dict(
                (_k, LatestPackets.from_dict(_v))
                for _k, _v in obj["LatestPackets"].items()
            )
            if obj.get("LatestPackets") is not None
            else None
        })
        return _obj


